# docker-compose up -d
version: '2'
services: 
    microservice:
        build: .
        image: node_fib_gen:1.0.0-alpine
        environment: 
        - PORT=5005
        ports: 
        - "5005:5005"
